# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='jiji.rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x08jiji.rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n\x04Tick\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"2\n\x0b\x41gentSource\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"7\n\x10ValidationResult\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"9\n\x12RegistrationResult\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"1\n\nAgentClass\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\";\n\x14\x41gentCreationRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\":\n\x13\x41gentCreationResult\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\x32\xa4\x03\n\x0c\x41gentService\x12\x34\n\x08NextTick\x12\x0e.jiji.rpc.Tick\x1a\x16.google.protobuf.Empty\"\x00\x12?\n\x08Validate\x12\x15.jiji.rpc.AgentSource\x1a\x1a.jiji.rpc.ValidationResult\"\x00\x12\x41\n\x08Register\x12\x15.jiji.rpc.AgentSource\x1a\x1c.jiji.rpc.RegistrationResult\"\x00\x12=\n\nUnregister\x12\x15.jiji.rpc.AgentSource\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x0fGetAgentClasses\x12\x16.google.protobuf.Empty\x1a\x14.jiji.rpc.AgentClass\"\x00\x30\x01\x12V\n\x13\x43reateAgentInstance\x12\x1e.jiji.rpc.AgentCreationRequest\x1a\x1d.jiji.rpc.AgentCreationResult\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TICK = _descriptor.Descriptor(
  name='Tick',
  full_name='jiji.rpc.Tick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='jiji.rpc.Tick.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.Tick.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=159,
)


_AGENTSOURCE = _descriptor.Descriptor(
  name='AgentSource',
  full_name='jiji.rpc.AgentSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.AgentSource.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.AgentSource.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=211,
)


_VALIDATIONRESULT = _descriptor.Descriptor(
  name='ValidationResult',
  full_name='jiji.rpc.ValidationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.ValidationResult.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.ValidationResult.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=268,
)


_REGISTRATIONRESULT = _descriptor.Descriptor(
  name='RegistrationResult',
  full_name='jiji.rpc.RegistrationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.RegistrationResult.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.RegistrationResult.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=327,
)


_AGENTCLASS = _descriptor.Descriptor(
  name='AgentClass',
  full_name='jiji.rpc.AgentClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.AgentClass.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.AgentClass.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=378,
)


_AGENTCREATIONREQUEST = _descriptor.Descriptor(
  name='AgentCreationRequest',
  full_name='jiji.rpc.AgentCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.AgentCreationRequest.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.AgentCreationRequest.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=439,
)


_AGENTCREATIONRESULT = _descriptor.Descriptor(
  name='AgentCreationResult',
  full_name='jiji.rpc.AgentCreationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='jiji.rpc.AgentCreationResult.latitude', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='jiji.rpc.AgentCreationResult.longitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=499,
)

_TICK.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Tick'] = _TICK
DESCRIPTOR.message_types_by_name['AgentSource'] = _AGENTSOURCE
DESCRIPTOR.message_types_by_name['ValidationResult'] = _VALIDATIONRESULT
DESCRIPTOR.message_types_by_name['RegistrationResult'] = _REGISTRATIONRESULT
DESCRIPTOR.message_types_by_name['AgentClass'] = _AGENTCLASS
DESCRIPTOR.message_types_by_name['AgentCreationRequest'] = _AGENTCREATIONREQUEST
DESCRIPTOR.message_types_by_name['AgentCreationResult'] = _AGENTCREATIONRESULT

Tick = _reflection.GeneratedProtocolMessageType('Tick', (_message.Message,), dict(
  DESCRIPTOR = _TICK,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.Tick)
  ))
_sym_db.RegisterMessage(Tick)

AgentSource = _reflection.GeneratedProtocolMessageType('AgentSource', (_message.Message,), dict(
  DESCRIPTOR = _AGENTSOURCE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.AgentSource)
  ))
_sym_db.RegisterMessage(AgentSource)

ValidationResult = _reflection.GeneratedProtocolMessageType('ValidationResult', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATIONRESULT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.ValidationResult)
  ))
_sym_db.RegisterMessage(ValidationResult)

RegistrationResult = _reflection.GeneratedProtocolMessageType('RegistrationResult', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONRESULT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.RegistrationResult)
  ))
_sym_db.RegisterMessage(RegistrationResult)

AgentClass = _reflection.GeneratedProtocolMessageType('AgentClass', (_message.Message,), dict(
  DESCRIPTOR = _AGENTCLASS,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.AgentClass)
  ))
_sym_db.RegisterMessage(AgentClass)

AgentCreationRequest = _reflection.GeneratedProtocolMessageType('AgentCreationRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTCREATIONREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.AgentCreationRequest)
  ))
_sym_db.RegisterMessage(AgentCreationRequest)

AgentCreationResult = _reflection.GeneratedProtocolMessageType('AgentCreationResult', (_message.Message,), dict(
  DESCRIPTOR = _AGENTCREATIONRESULT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jiji.rpc.AgentCreationResult)
  ))
_sym_db.RegisterMessage(AgentCreationResult)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class AgentServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NextTick = channel.unary_unary(
        '/jiji.rpc.AgentService/NextTick',
        request_serializer=Tick.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Validate = channel.unary_unary(
        '/jiji.rpc.AgentService/Validate',
        request_serializer=AgentSource.SerializeToString,
        response_deserializer=ValidationResult.FromString,
        )
    self.Register = channel.unary_unary(
        '/jiji.rpc.AgentService/Register',
        request_serializer=AgentSource.SerializeToString,
        response_deserializer=RegistrationResult.FromString,
        )
    self.Unregister = channel.unary_unary(
        '/jiji.rpc.AgentService/Unregister',
        request_serializer=AgentSource.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetAgentClasses = channel.unary_stream(
        '/jiji.rpc.AgentService/GetAgentClasses',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=AgentClass.FromString,
        )
    self.CreateAgentInstance = channel.unary_unary(
        '/jiji.rpc.AgentService/CreateAgentInstance',
        request_serializer=AgentCreationRequest.SerializeToString,
        response_deserializer=AgentCreationResult.FromString,
        )


class AgentServiceServicer(object):

  def NextTick(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Validate(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Register(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unregister(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgentClasses(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAgentInstance(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NextTick': grpc.unary_unary_rpc_method_handler(
          servicer.NextTick,
          request_deserializer=Tick.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Validate': grpc.unary_unary_rpc_method_handler(
          servicer.Validate,
          request_deserializer=AgentSource.FromString,
          response_serializer=ValidationResult.SerializeToString,
      ),
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=AgentSource.FromString,
          response_serializer=RegistrationResult.SerializeToString,
      ),
      'Unregister': grpc.unary_unary_rpc_method_handler(
          servicer.Unregister,
          request_deserializer=AgentSource.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetAgentClasses': grpc.unary_stream_rpc_method_handler(
          servicer.GetAgentClasses,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=AgentClass.SerializeToString,
      ),
      'CreateAgentInstance': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAgentInstance,
          request_deserializer=AgentCreationRequest.FromString,
          response_serializer=AgentCreationResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'jiji.rpc.AgentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaAgentServiceServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def NextTick(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Validate(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Register(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Unregister(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def GetAgentClasses(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def CreateAgentInstance(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaAgentServiceStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def NextTick(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  NextTick.future = None
  def Validate(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Validate.future = None
  def Register(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Register.future = None
  def Unregister(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Unregister.future = None
  def GetAgentClasses(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  def CreateAgentInstance(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  CreateAgentInstance.future = None


def beta_create_AgentService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('jiji.rpc.AgentService', 'CreateAgentInstance'): AgentCreationRequest.FromString,
    ('jiji.rpc.AgentService', 'GetAgentClasses'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
    ('jiji.rpc.AgentService', 'NextTick'): Tick.FromString,
    ('jiji.rpc.AgentService', 'Register'): AgentSource.FromString,
    ('jiji.rpc.AgentService', 'Unregister'): AgentSource.FromString,
    ('jiji.rpc.AgentService', 'Validate'): AgentSource.FromString,
  }
  response_serializers = {
    ('jiji.rpc.AgentService', 'CreateAgentInstance'): AgentCreationResult.SerializeToString,
    ('jiji.rpc.AgentService', 'GetAgentClasses'): AgentClass.SerializeToString,
    ('jiji.rpc.AgentService', 'NextTick'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
    ('jiji.rpc.AgentService', 'Register'): RegistrationResult.SerializeToString,
    ('jiji.rpc.AgentService', 'Unregister'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
    ('jiji.rpc.AgentService', 'Validate'): ValidationResult.SerializeToString,
  }
  method_implementations = {
    ('jiji.rpc.AgentService', 'CreateAgentInstance'): face_utilities.unary_unary_inline(servicer.CreateAgentInstance),
    ('jiji.rpc.AgentService', 'GetAgentClasses'): face_utilities.unary_stream_inline(servicer.GetAgentClasses),
    ('jiji.rpc.AgentService', 'NextTick'): face_utilities.unary_unary_inline(servicer.NextTick),
    ('jiji.rpc.AgentService', 'Register'): face_utilities.unary_unary_inline(servicer.Register),
    ('jiji.rpc.AgentService', 'Unregister'): face_utilities.unary_unary_inline(servicer.Unregister),
    ('jiji.rpc.AgentService', 'Validate'): face_utilities.unary_unary_inline(servicer.Validate),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_AgentService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('jiji.rpc.AgentService', 'CreateAgentInstance'): AgentCreationRequest.SerializeToString,
    ('jiji.rpc.AgentService', 'GetAgentClasses'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
    ('jiji.rpc.AgentService', 'NextTick'): Tick.SerializeToString,
    ('jiji.rpc.AgentService', 'Register'): AgentSource.SerializeToString,
    ('jiji.rpc.AgentService', 'Unregister'): AgentSource.SerializeToString,
    ('jiji.rpc.AgentService', 'Validate'): AgentSource.SerializeToString,
  }
  response_deserializers = {
    ('jiji.rpc.AgentService', 'CreateAgentInstance'): AgentCreationResult.FromString,
    ('jiji.rpc.AgentService', 'GetAgentClasses'): AgentClass.FromString,
    ('jiji.rpc.AgentService', 'NextTick'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
    ('jiji.rpc.AgentService', 'Register'): RegistrationResult.FromString,
    ('jiji.rpc.AgentService', 'Unregister'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
    ('jiji.rpc.AgentService', 'Validate'): ValidationResult.FromString,
  }
  cardinalities = {
    'CreateAgentInstance': cardinality.Cardinality.UNARY_UNARY,
    'GetAgentClasses': cardinality.Cardinality.UNARY_STREAM,
    'NextTick': cardinality.Cardinality.UNARY_UNARY,
    'Register': cardinality.Cardinality.UNARY_UNARY,
    'Unregister': cardinality.Cardinality.UNARY_UNARY,
    'Validate': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'jiji.rpc.AgentService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
