
global._babelPolyfill = false;
import "babel-core/polyfill"

import "./specs/model/preferences-spec"
import "./specs/model/agents/agent-sources-spec"
import "./specs/model/agents/agent-classes-spec"
import "./specs/model/trading/intervals-spec"
import "./specs/model/trading/pairs-spec"
import "./specs/model/trading/rates-spec"
import "./specs/model/trading/backtests-spec"
import "./specs/model/trading/backtest-builder-spec"
import "./specs/model/trading/agent-setting-builder-spec"
import "./specs/remoting/transformer-spec"
import "./specs/remoting/url-resolver-spec"
import "./specs/remoting/xhr-manager-spec"
import "./specs/utils/dates-spec"
import "./specs/utils/observable-spec"
import "./specs/utils/objects-spec"
import "./specs/utils/numbers-spec"
import "./specs/utils/collections-spec"
import "./specs/utils/validation/validation-functions-spec"
import "./specs/utils/validation/validators-spec"
import "./specs/viewmodel/agents/agent-source-editor-spec"
import "./specs/viewmodel/chart/slider-spec"
import "./specs/viewmodel/chart/positions-spec"
import "./specs/viewmodel/chart/candle-sticks-spec"
import "./specs/viewmodel/chart/graph-coordinate-calculator-spec"
import "./specs/viewmodel/chart/graphs-spec"
import "./specs/viewmodel/trading-summary/trading-summary-model-spec"
import "./specs/viewmodel/utils/date-formatter-spec"
import "./specs/viewmodel/utils/string-formatter-spec"
import "./specs/viewmodel/utils/number-formatter-spec"
import "./specs/viewmodel/widgets/table-model-spec"
