# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: health_check.proto for package 'jiji.rpc'

require 'grpc'
require 'health_check_pb'

module Jiji
  module Rpc
    module HealthCheckService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'jiji.rpc.HealthCheckService'

        rpc :Status, Google::Protobuf::Empty, GetStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
