# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health_check.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "jiji.rpc.GetStatusResponse" do
    optional :status, :string, 3
  end
end

module Jiji
  module Rpc
    GetStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jiji.rpc.GetStatusResponse").msgclass
  end
end
