# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "jiji.rpc.LoggingRequest" do
    optional :instance_id, :string, 1
    optional :log_level, :string, 2
    optional :message, :string, 3
  end
end

module Jiji
  module Rpc
    LoggingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jiji.rpc.LoggingRequest").msgclass
  end
end
